### ISSUE TITLE
Docker support !

### ISSUE THREAD

**Issue by seedboxer** [Woahai321/SeerrBridge#2]
Would love to see this is a docker / compose. Thank you !

**Comment by Woahai321** [comment]
@seedboxer I have a version locally that I have tested to work on this.

Just need it properly tested.

Hopefully I can release it soon, or someone can come along and implement it :)

**Comment by Woahai321** [comment]
Just need to make a new release, but Docker support has been implemented :)

Let me know if there are any issues (in a new issue)!
